### PR TITLE
adds location href and limitation to return value

### PR DESCRIPTION
**Pull request by olli-gold**
Hi there, I have added two values to the DAIA driver, that we need in TUBfind - perhaps they are also usefull for others.

### CODE REVIEW

**Comment by demiankatz** [comment]
The locationhref seems like a useful enhancement generally speaking. Do you want to add some template changes to make that a new part of the ILS driver spec that we can document?

Is the 'limitation' field something that could be passed through the existing 'notes' field, which does not currently appear to be getting used by the DAIA driver? If this needs to be differentiated, we can keep it as-is, but it would be better if we could get away with utilizing an existing mechanism.

**Comment by olli-gold** [comment]
Thank you for your feedback, Demian! 

I will add the locationhref to the templates to document where they could be used.

I'm not sure about treating the limitation as a note. The limitation element in DAIA is used to mark limitations in certain availabilities (for example for presence use or for loan). The note is a bit more unspecific and may contain anything related to the copy or the item, that is described in the DAIA output. So I would not put the two elements together. This makes it also more flexible to display the limitation for a certain copy while the note can be displayed in a broader context.

**Comment by demiankatz** [comment]
Thanks -- that makes sense; I mainly mentioned 'notes' because the DAIA driver does not currently appear to be using it.

One question, though: where does locationhref get used? I'm only seeing 'limitation' added to the templates so far....

**Comment by olli-gold** [comment]
locationhref is only getting used in the AjaxController so far. We could put it also into the templates, but for us it was enough to see it in the result list.

**Comment by demiankatz** [comment]
Perhaps I'm misunderstanding its purpose -- I thought the idea was that, if it was set, you would put an `<a href...>` around the location text in the template...  or is this not a user-oriented URL?

**Comment by olli-gold** [comment]
Yes, right, this was the idea. And this is exactly what we are doing, but only with Ajax in the result list. We could also add it to the main template for the full record view, but for us its currently enough to display that link in the result list.

**Comment by olli-gold** [comment]
I have decided to implement your suggestion however and to add locationhref also to the templates. Even if we are not using it, it may be useful for others and so it completes the PullRequest, doesn't it?

**Comment by demiankatz** [comment]
That ought to do it. I'll try to merge this next week after the blueprint theme is removed. (I'm going to create a branch where blueprint can continue to be maintained, in case somebody decides they want to pick up development of that theme... thus, I don't want to merge new functionality to other themes until I've separated that from master; should happen on Tuesday!)

**Comment by olli-gold** [comment]
As far as I see, my PR has not been included in the recent merge. Should I renew it against the VuFind master?

**Comment by demiankatz** [comment]
Sorry about that! I was trying to figure out where it was -- I think I've been commenting and reviewing this on the assumption that it was already a PR against master, and then I was quite puzzled yesterday when I couldn't find it. If you have time to renew this against master, that might save me a few minutes, but if not, I think I can find a way to merge it in as-is. I guess we'll see who finds the time first; as I mentioned, I'm probably not going to have a whole lot of coding time today, but I'll definitely be able to do it tomorrow.

**Comment by olli-gold** [comment]
I have opened a new PR for the VuFind master (number 451). So this one can be ignored.

**Comment by demiankatz** [comment]
Thanks. I'll close this now, and try to get that merged in time for the 2.5 release.

**Pull request closed without merging**
