### PR TITLE
prepares unit test for PAIA driver

### PR DESCRIPTION
**Pull request by olli-gold**
This PR prepares some test cases and supplies some fixtures for the tests. Some tests are failing or marked as skipped and need some more work, but this is supposed to be a skeleton to get the tests working.

### CODE REVIEW

**Comment by olli-gold** [comment]
I see that some of the fixture files are not correct currently and will fail if they are used. This also needs to be fixed (if we need all of the fixtures).

**Comment by lahmann** [comment]
Regarding 4ae3a23 : good point, it looks like there's a typo in the Wiki documentation for getHolding (see https://vufind.org/wiki/development:plugins:ils_drivers#getholding) as it defines the return array of getHolding with the field `location_href` whereas (if at all) `locationhref` is used everywhere in the code (I have to admit I did not check the code but stuck to the documentation when mapping the getHolding return value).
@demiankatz what do you think? Should we change the field name in the Wiki to `locationhref`?

**Comment by demiankatz** [comment]
I've corrected the wiki -- as you say, the underscore is not present in the existing code, and it's easier/safer/less disruptive to adjust the documentation to reflect the running code than to do the reverse. Good catch!

**Comment by lahmann** [comment]
@olli-gold great tests! Thanks a lot! I manually merged this PR into https://github.com/vufind-org/vufind/pull/729 to reduce the commit history (see b2147db)

**Pull request closed without merging**
